name: Deploy Prod
on:
  pull_request:
    types:
      - labeled

jobs:
  assign:
    name: Assign new HIP number
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'janitor:assign') }}

    steps:
      - name: Sia Skynet talk
        id: janitor
        run: |
          mkdir .janitor
          last=`curl https://0004hoej776q85oio0seben1h4elul6m6jve8q67hc3bla4t257k1a8.siasky.net/assign -s`
          next="$((last + 1))"
          echo $next > .janitor/assign
          echo "::set-output name=next::$(printf %4s $next | tr ' ' 0)"
        shell: bash
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "**Assigning new HIP number**\nPlease, update this PR and use `HIP-${{ steps.janitor.outputs.next }}`"
            })
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "janitor:assign"
            })

      - name: Save to Skynet
        uses: kwypchlo/deploy-to-skynet-action@main
        with:
          upload-dir: .janitor
          registry-seed: ${{ secrets.REGISTRY_SEED || '' }}
